version: 1.0.{build}
environment:
  nodejs_version: "4.1.2"
init:
- ps: Install-Product node $env:nodejs_version
- npm install -g npm@3
- set PATH=C:\Users\appveyor\AppData\Roaming\npm;%PATH%
- npm -v
- node -v
- npm cache clean
test: false
install:
- cd src
- npm install
- npm test
build: false
